version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: my_image_front:latest
    #hostname: finaxys-Latitude-E5470
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "4000:80"
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    extra_hosts:
      - "MV1:192.168.99.100"
      - "MV2:192.168.99.101"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
